# development:
#   adapter: async
#   # adapter: redis
#   url: redis://localhost:6379/1
#   # url: redis://:loardmanoj@redis-14661.c8.us-east-1-2.ec2.cloud.redislabs.com:14661
#   # url: redis://password@redis-17172.c10.us-east-1-2.ec2.cloud.redislabs.com:17172
# test:
#   adapter: async

# production:
#   adapter: redis
#   url: redis://localhost:6379/1
#   # url: redis://password@redis-17172.c10.us-east-1-2.ec2.cloud.redislabs.com:17172

# # redis-17172.c10.us-east-1-2.ec2.cloud.redislabs.com:17172
